# Generated by Django 4.0.5 on 2022-07-24 01:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_description_category_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_en',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='categories.category', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_ru',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='categories.category', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
