# Generated by Django 4.0.5 on 2022-07-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_setting_facebook_setting_instagram_setting_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(verbose_name='Описание сайта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Электронная почта сайта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на facebook'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на linkedin'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Логотип сайта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на twitter'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на youtube'),
        ),
    ]
