# Generated by Django 4.0.5 on 2022-07-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currency',
            field=models.CharField(choices=[('KGS', 'KGS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('Договорная', 'Договорная')], default='Договорная', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(default='+996 708 89 03 08', max_length=100),
        ),
    ]
