# Generated by Django 4.0.5 on 2022-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
