# Generated by Django 4.0.5 on 2022-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Действителный'),
        ),
    ]
