# Generated by Django 4.0.5 on 2022-07-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_favoritepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritepost',
            name='favirite_posts',
            field=models.BooleanField(default=False, verbose_name='Закладки'),
        ),
    ]
