# Generated by Django 4.0.5 on 2022-07-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_favoritepost_favirite_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritepost',
            name='favirite_posts',
        ),
    ]
