# Generated by Django 4.0.5 on 2022-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_favoritepost_favirite_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.BooleanField(default=False, verbose_name='В закладках'),
        ),
    ]
