# Generated by Django 4.0.5 on 2022-07-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarks',
        ),
    ]
