# Generated by Django 4.0.5 on 2022-07-24 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0003_category_parent_en_category_parent_ru_and_more'),
        ('posts', '0012_remove_post_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='categories.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='categories.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Человекопонятный URL (само генерация)'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Человекопонятный URL (само генерация)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='valid_en',
            field=models.BooleanField(default=True, verbose_name='Действителный'),
        ),
        migrations.AddField(
            model_name='post',
            name='valid_ru',
            field=models.BooleanField(default=True, verbose_name='Действителный'),
        ),
    ]
